Feature/upgrade gradle to 8
TNG/jgiven-intellij-plugin pull request #125
Opened 2023-07-28 11:04 UTC by l-1squared

2023-07-30 15:29 UTC, klassm requested changes
Please also squash commits / bring them a bit into order.

2023-07-30 15:29 UTC, klassm commented on src/main/resources/META-INF/plugin.xml
> -    <idea-version since-build="163.6110.112"/>
Why did you increase this? Do you know use APIs only available since then?

2023-07-30 15:29 UTC, klassm commented on src/test/java/com/tngtech/jgiven/reference/ScenarioStateUsageProviderIntegrationTest.kt
> -package com.tngtech.jgiven.reference
Can we make this test work again? Are you sure this test never worked?

2023-07-30 15:29 UTC, klassm commented on .github/workflows/build.yml
>        run: ./gradlew buildPlugin test
At least here tests were executed...

2023-08-01 04:23 UTC, l-1squared commented on src/main/resources/META-INF/plugin.xml
> -    <idea-version since-build="163.6110.112"/>
I guess so. The IntelliJ plugin basicly stated in the build that it would increase the number, and I thought, well, then we can also increase it manually. I'd wager that the change in question was the addition to the constructor

2023-08-01 04:23 UTC, l-1squared commented on src/test/java/com/tngtech/jgiven/reference/ScenarioStateUsageProviderIntegrationTest.kt
> -package com.tngtech.jgiven.reference
It failed on master. I can double check if you want to

2023-08-01 04:24 UTC, l-1squared commented on src/test/java/com/tngtech/jgiven/reference/ScenarioStateUsageProviderIntegrationTest.kt
> -package com.tngtech.jgiven.reference
Or to be more precise, it was not exectuted on master, and when I made it, it failed

2023-08-01 04:24 UTC, l-1squared commented on .github/workflows/build.yml
>        run: ./gradlew buildPlugin test
?

2023-08-01 04:27 UTC, l-1squared commented
> Please also squash commits / bring them a bit into order.

I would like to ask for some guidance here; I can squash them, but we are doing three somewhat connected updates here so that may not be a good idea. And in my opinion, they are in the order of "update something; try to fix all complaints; update something else". I don't no what kind of order you would prefer.

2023-08-01 05:44 UTC, klassm commented
> I would like to ask for some guidance here; I can squash them, but we are doing three somewhat connected updates here so that may not be a good idea. And in my opinion, they are in the order of "update something; try to fix all complaints; update something else". I don't no what kind of order you would prefer.

Well there are various infrastructure upgrades, that can be grouped. I guess we don't need three commits updating Gradle, do we? 
Same goes for the actual implementation - Remove deprecations, Update since field, Update intellij plugin somewhat belong together, don't they? So this is rather not about what the commit is doing than about what the intention is.

2023-08-01 05:44 UTC, klassm commented on .github/workflows/build.yml
>        run: ./gradlew buildPlugin test
./gradlew buildPlugin test

2023-08-01 05:44 UTC, klassm commented on src/test/java/com/tngtech/jgiven/reference/ScenarioStateUsageProviderIntegrationTest.kt
> -package com.tngtech.jgiven.reference
Still it would be nice to have the test again.

2023-08-02 04:39 UTC, l-1squared commented on .github/workflows/build.yml
>        run: ./gradlew buildPlugin test
so, I guess we're again talking about the ScenarioUserProviderTest...
I captured a screenshot from master, to show that this particular test is in fact not picked up: 
![image](https://github.com/TNG/jgiven-intellij-plugin/assets/30831153/c0222ae9-1db8-4f30-97b6-57cd921eb426)

If I annotate with `@Test` the following happens: 
![image](https://github.com/TNG/jgiven-intellij-plugin/assets/30831153/a202d2f8-cfe9-480c-955d-1910a5fe652a)

I guess we have a bug somewhere in the software responsible for picking up those tests, because one annotation sufficed to activate all four tests. 
I tried this with JVM 11 as the backing machine. (JVM -8 seemed to be already incompatible). In any case, the issue with this test is that the LibraryTestUtil cannot find the source code location:
![image](https://github.com/TNG/jgiven-intellij-plugin/assets/30831153/b311a19a-2704-4994-ab72-1c28d0a85fb9)

My guess is, however, that this is an important part of the test and I have absolutely no idea on how to replicate such a feature. If you can be of any help here, I would greatly appreciate it.

2023-08-02 04:44 UTC, l-1squared commented
> 



> > I would like to ask for some guidance here; I can squash them, but we are doing three somewhat connected updates here so that may not be a good idea. And in my opinion, they are in the order of "update something; try to fix all complaints; update something else". I don't no what kind of order you would prefer.
> 
> Well there are various infrastructure upgrades, that can be grouped. I guess we don't need three commits updating Gradle, do we? Same goes for the actual implementation - Remove deprecations, Update since field, Update intellij plugin somewhat belong together, don't they? So this is rather not about what the commit is doing than about what the intention is.

The updates are not quite independent though. For instance, the newest intellij Plugin talks about Java 17 requirements and I think  the old kotlin version (or was it the old intelliJ plugin) was incompatible with Gradle-8. So I cannot reorder or squash commits partially.  

I can, if you wish, squash everything into one commit, and name it "Grand build system refurbishment"

2023-08-02 04:45 UTC, l-1squared commented on src/test/java/com/tngtech/jgiven/reference/ScenarioStateUsageProviderIntegrationTest.kt
> -package com.tngtech.jgiven.reference
Agree with you. But as I detailed below, I have no working system to Jump off of, and I am not knowledgeable enough to rewrite this test from scratch.

2023-09-15 09:39 UTC, merged